### PR TITLE
Updated after discussions

### PR DESCRIPTION
**Pull request by clockworkgr**
This is the updated fee proposal after discussions in: https://github.com/bitshares/committee-tools/pull/1

The current vs proposal fee differences can be seen here:

https://gist.githubusercontent.com/clockworkgr/59c3e1c655720bc1c2c1782547d38bd9/raw/318c1d7193ed988d77b2ea411bc46a26bb6de9cb/proposal.txt

IMPORTANT NOTE: Due to BTS price falling, ALL operations are currently cheaper (in USD terms) then the previously agreed Fee Schedule. The difference is 3.378x.

Hence, everything in the gist above that has a difference of less than 3.378x is proposed to be cheaper than the existing fee schedule in USD terms. Anything higher is proposed more expensive.

(Point being, even if fee schedule didn't change, simply updating BTS values to account for BTS price drop would still make everything 3.378x more expensive in BTS terms)

This will be posted for further discussion in the forums.

### CODE REVIEW

**Comment by clockworkgr** [comment]
Pending a clarification from @xeroc on whether the scripts use feed price or market price. If not using feed price, current fees are actually 30% lower (and proposal difference is greater) due to USDs broken peg.

**Comment by froooze** [comment]
The fees are now fine for limit order create and cancel. Good work!

**Comment by clockworkgr** [comment]
There is also always the option of keeping increases smaller (or not at all) and increasing the network cut instead. However I believe that will be much harder to reach consensus on.

**Comment by froooze** [comment]
20% network and 80% referral is the ratio of the pareto principle (fair). We should not change this.

**Comment by clockworkgr** [comment]
Pareto principle  refers to a cause and effect scenario. Totally unrelated to this which is simply an arbitrary split.

**Comment by froooze** [comment]
@clockworkgr 
When I take 15x for the transfer fee = 1.5BTS = 0.06 and not 0.08$?

**Comment by thul3** [comment]
When will be the next update about ?
Am asking cause the "basic account create" will be to high for the upcoming refferal program in may where majority of accounts won't be used much and also need to be prepaid.

**Comment by clockworkgr** [comment]
Once I get further feedback (and possibly optimize further) I will put it on-chain for voting by the committee. Probably on a somewhat long expiration (2 weeks/a month) to allow for people to further voice any final concerns.

Basic account changes from 10 cents to 25 cents. Yes, it's more expensive but we have a HUGE amount of spam/unused accounts.

New referral program should GREATLY increase returns for referrers so the extra 15 cents should not be an issue imho. @xeroc seeing as you run the largest faucet, wanna weigh in on this?

**Comment by froooze** [comment]
@clockworkgr
The spamer doesn't pay for registration fees, but the registrar does. Why should rising registration fees reduce spam accounts?
The unused accounts come maybe from the low liquid markets or the user has no real use case for the  Account. This problem is not solved by rising onboarding fees. 


> When I take 15x for the transfer fee = 1.5BTS = 0.06 and not 0.08$

Could you explain these numbers?

**Comment by clockworkgr** [comment]
> @clockworkgr
> The spamer doesn't pay for registration fees, but the registrar does. Why should rising registration fees reduce spam accounts?

actually a large number of accounts are created by 3rd party apps (usually with a common prefix)...spam accounts are not really due to the standard faucets

> The unused accounts come maybe from the low liquid markets or the user has no real use case for the Account. This problem is not solved by rising onboarding fees.
> 
> > When I take 15x for the transfer fee = 1.5BTS = 0.06 and not 0.08$
> 
> Could you explain these numbers?

Yeah, current chain prices are actually 30% lower, the script that produces the gist uses the GS price rather than the feed price

**Comment by xeroc** [comment]
Can we move forward here now? It's been **weeks** since we've started discussion and **weeks** since last feedback was given. I'd say, let's put this proposal on-chain and tune the fee.

**Comment by bangzi1001** [comment]
Better do it now. 

Feb 5, 2019 is Chinese New Year and is two weeks from now. Chinese will busy to prepare for their new year and may take up to 15 Days break from Chinese New Year until Chap Goh Mei Festival.

**Comment by clockworkgr** [comment]
yeah...sorry...been ridiculously busy and swamped with work after the holidays.

have you updated the script to use feed price rather than settlement/market price?

**Comment by xeroc** [comment]
I am merging this and will provide a proposal for committee to vote for as soon as possible.
Expiration time will most probably be around 2 weeks to give notice to everyone.

**Comment by crypto-1** [comment]
CryptoBridge's official comment on this matter:

While we fully appreciate the current difficulties the marketplace is causing for all projects, we have been calculating the changes proposed and are alarmed at what the results for the end-users will be: It raises limit orders by 45x and transfers (withdrawals) by 13x.

Our own asset issue operations (deposits) are increased by 13x as well. That means each deposits costs us some $0.05 or $0.01 after LTM (lifetime membership). The majority of our users are miners depositing amounts worth much less than $0.01 on average. The asset issue fee increase would increase our costs from $407 to $5285 or 1300%.

We hope that as the largest user in the BTS ecosystem (>80% market share) our perspective will inform some options (reasonable of course). CryptoBridge has had the privilege of being a consistent source of BTS volume via fees and would like to be on footing that will help us to further expand that.

While we do respect the need for BitShares to remain profitable, a 3300% fee increase for users (without any thorough effort to inform them outside of github and bitsharestalk.org discussions) is certain to cause and acute and destructive backlash. In addition, the high order and cancel fees effectively render the all liquidity bots into an exercise in negative revenue production.

Additionally, the proposed vesting balance create function from 5.8 BTS to 52.9 BTS is a 9x increase. The negative impact on creating staking positions would further undermine one of our most important value propositions. Not many users would be interested in staking when it costs $1-2 to open a new staking position.

The likelihood that the average user will take the time to research who or what is responsible for the proposed fee increase is incredibly low. We can predict this with certainty, having been informed by the experience we’ve had in making consistent efforts to educate these average users. We still must refer users to a number of basic informational and support resources on a routine basis. Without a high degree of easy-to-understand materials and support agents to deliver such changes, the outcome of implementing these will be difficult to manage and lead to people moving away from using BTS platforms.

While this discussion has been ongoing among the most knowledgeable and active participants related to BitShares, this is not a representation of aggregate of users. There has been little to no communication outside of the github and bitsharestalk.org environment, and implementing this proposal in such a way will be a shock and surprise to the vast majority.

These users will blame CryptoBridge, and even if we provide explanations and refer to Bitshares the end user’s perception of the platform will be irrevocably damaged. The chance that they will never use Bitshares or CryptoBridge again at all is very high. Even if the fees are reduced afterward, the damage will have been done and they will be unlikely to return.

To the outsider (who may not even know how committee proposals work) it may seem like Bitshares appears to simply be greedy being that they may not fully understand the need for them or why they have increased so dramatically.

Gateways are dis-incentivized to choose BitShares if they are unable to plan long-term due to the huge volatility in fee structures moving forward. No new gateway would want to operate under such extremely precarious conditions, and would choose a more stable environment with better expectations of how to manage their revenue flows.

In any case, it seems suicidal for any business to increase their prices by such a degree. Increments of 
100 to 200% can be justified when viewed from a USD price pases, a 1000 to 5300% leap cannot. Users will migrate to other platforms like Waves which have more competitive fees.

Our counter-proposal would be to raise the fees to keep the BTS blockchain profitable, but not to such 
immediate and acute expense to the users and gateways (both of which are the backbone of BTS). While the actual ratios are sensible, we would just like to propose a much lower increase (such as 25-35% of the proposed fee increasement). This would still mean a 15-20x fee increase for traders and liquidity bots.

Ideally, CryptoBridge would like to opt for a more moderate fee increase of 100 to 200% which we may assist in communicating to our common users. If unable to avoid the proposed sharp jump upward, we can only concede to 15-20% of the suggested fee increase. Users and gateways will still be punished in this instance, but it would significantly dwarf the potential 5300% increase to a “mere” 700%.

The outcome of the above will really only serve to create a loss for both BitShares and CryptoBridge. Volume will plummet. CryptoBridge may be forced to migrate to another blockchain if our users will not accept this fee increase, as our top priority is the well-being of our users. We cannot operate a successful gateway without being able to balance the ratio of costs levied on both our users and the gateway itself. 

Summary: Our users are now paying to Bitshares $207,48 per month on average, with the new fee schedule it'd be $6871,14 (a 3300% increase). We strongly disagree which such a sharp fee increase as we think it might severely damage our business.

**Comment by PassiveCoin** [comment]
It's always the same story. If something work well, people try to collect more fees ... 
Bitshares bosses forgot that BitShares is not the only blockchain.
Bear market is a poor excuse for such prices increase as this trend hit all blockchains and projects.
Greed is not a good adviser.
After such price increase you will experience outflow of small fishes from trading on CryptoBridge and similar exchanges, causing volume drop ... causing outflow of next traders ... and so on.
Perhaps exchanges gonna evaluate go back to own blockchains or move to one with lower fees. 
Ladies & gentelmans from committee-account - remember grred iwas never good adviser.

**Comment by xovercoin** [comment]
XOV is a new entrant on the Bitshares ecosystem and so we don't feel qualified yet to make a full analysis of the proposed fee increase but on face value, it would seem to be disproportionately high. The fall in the price of Bitshares is likely to be due to competition from other blockchains, not enough marketing exposure and momentum, and in my opinion, a much needed mobile UI to support the desktop version of the DEX. I would like to see some sort of alliance involving senior representatives from all the BTS DEX including us so that we can look at the issues from a commercial perspective. The long term success depends on both the technical AND commercial development of BitShares. We should be acting in unison to protect what we have rather than acting in silos (perhaps a DEX operators subcommittee). This committee could recommend actions that will entice new customers to the network and make it more attractive for new operators.

**Comment by Nesh-01** [comment]
Simply put, I don't see Bitshares having a bright future if this proposal gets implemented. Liquidity bots will be killed or at least heavily crippled, many users won't accept such a sharp increase of fees and move to other ecosystems, exchanges will not only have increased costs but will also lose many customers, making them less profitable and possibly make them go bankrupt or force them to move to another blockchain with cheaper fees.
I don't think many people will object a moderate increase if it is neccesary, but a ~3300% increase looks like a (maybe slow) deathblow to me.

You can also think about it this way: DEXes can only flourish as long as the fees are so low that the users barely think about them. Once they become too high people will consider the fee paid for every operation they do, effectively killing the user experience of DEXes and almost no one will be willing to choose such one over centralized exchanges.

**Comment by PassiveCoin** [comment]
I like the post above and support it!.
The most funny thing is that this so-called BitShares committee can come one day with voting fees up by 3000% or any other figure, out of the blue. 
LoL 
They do not care about businesses operate on top of BTS blockchain nor care about the future of the whole ecosystem. How this greedy committee wants toi attract long-term business is a mystery for me. 
After such drastic move, no one gonna risk opening exchange or other project based on top of BTS.
Crayziness!
One day (in the future) they could vote again fees up by e.g. 1000%.
How people can plan their projects in such envoironment? Someone ready to explain me?

**Comment by Cryptotho** [comment]
I can't believe any project expecting other projects to use their platform suggests these huge price increases. Hopefully the posts above are enough to reconsider.

**Comment by hoha21** [comment]
If you want to compensate the low price to pay your bills in USD, peg the fee to the USD. Otherwise there will a problem with too high or too low fee returns.

**Comment by CryptoKong** [comment]
> I like the post above and support it!.
> The most funny thing is that this so-called BitShares committee can come one day with voting fees up by 3000% or any other figure, out of the blue.
> LoL
> They do not care about businesses operate on top of BTS blockchain nor care about the future of the whole ecosystem. How this greedy committee wants toi attract long-term business is a mystery for me.
> After such drastic move, no one gonna risk opening exchange or other project based on top of BTS.
> Crayziness!
> One day (in the future) they could vote again fees up by e.g. 1000%.
> How people can plan their projects in such envoironment? Someone ready to explain me?

this is absolute nonsense. this has been in discussion for a very long time but no one bothered to get involved in the conversation until now. The BitShares blockchain operates at approx 90% loss, what do you think will happen to exchanges when the blockchain comes to a standstill when there is no money to pay witnesses? Please everyone getting involved in this discussion because they saw a big number on cryptobridges tweet, educate yourself a little on the subject before commenting.

**Comment by CryptoKong** [comment]
I agree with CryptoBridge that the increases should be staggered, this will allow us to better gauge any gradual drop offs in liquidity providers/ users rather than potentially experiencing a cliff edge drop that cannot be regained.

**Comment by technologiespro** [comment]
Bitshares Blockchain was announced as being able to hold up to 100k/tps.
Currently looking at the block explorer, transactions are much less.
Why use high speed blockchain txs, if it is very expensive?
Due to the increase price, the number of tx will decrease.
Then there is no meaning in the declared speed, it will never be claimed.

**Comment by gCAN9** [comment]
I understand that the current market situation and its long duration has brought many - otherwise stable, viable and profitable - projects, to their knees. I also understand and agree that there has to be a reaction to such a situation, to avoid the complete failure of vital parts and processes. Of course there are various ways to tackle any challenge and I’m sure Bitshares as a project would like to survive and any decisions will be made with the best of the project in mind - not only short-term but especially long-term. 

Now DEXes already have inherent challenges (like speed, fees, UI, ease of use and more) that they have to manage in order to be competitive, stay alive and grow. It would surely be beneficial to take these into serious consideration when choosing a certain path for the future, in order to improve on these challenges and maybe eliminate some of them. And certainly not to make them worse, by increasing their influence and impact. 

The competition is strong (Waves has been mentioned, Binance DEX is underway) and they already have (or most certainly will, in Binance’s case) addressed several of the challenges DEXes face. 

I would like to encourage a different approach, which may include thinking of other ways to make Witnesses profitable, either by finding ways to lower their upkeep or by working on other aspects like chain performance that could have an impact on costs. 

One thing is certain, an increase in fees like the proposed one, is only a very short-term solution that will bring more problems with it than solutions.

**Comment by NorthmanAK** [comment]
I've been using Crypto-Bridge since they launched, the platform is great and the support is excellent. I'd hate to see users run away to a centralized exchange because of the fees getting out of control. Less users at a higher rate will not help in the long run. I would support the same fee increase that CB stated above.

**Comment by PassiveCoin** [comment]
My BTS voting rights too low to have any impact on this voting game. I will vote by proxy - CryptoBridge. 
... and you know, they charged 0.00807 BTS for this pleasure of moving voting rights. Every movement on BTS blockchain is taxed. 
LoL ... You probably "collect taxes" better than govern. :D 

CryptoKong says, quote: "The BitShares blockchain operates at approx 90% loss"
Then increase fees by 100% and improve yourself. As for my knowledge, every business try to improve product/service when implementing such big fees increase.
No need to increase fees by 3000% and see outflow of BTS users.
We all suffer from this crypto-winter, not only BTS blockchain.

**Comment by daveydd** [comment]
I'd say, increase the fees to a level that the blockchain is profitable again, and peg it against the dollar to prevent future discussions. Increasing it with a crazy number will sure kill businesses like Cryptobridge, thus killing the bitshares blockchain itself. Make sure that both parties will have a healthy flow of income / cost structure and we are all happy!

**Comment by xeroc** [comment]
**FYI**:
The current fee schedule has been postponed (proposal is no longer approved on-chain)

Instead, the old fee schedule will be redeployed to adopt for BTS:USD price change, first.
That will result in a consistent 4.364x price increase due to the BTS:USD volatility.

Further updates will be provided.

**Comment by CryptickCryptick1** [comment]
From a business standpoint I completely support the higher fees.  For a complete explanation and a good discussion on it see this post. https://steemit.com/bts/@cryptick/why-bitshares-need-sustainable-pricing

**Comment by linkara** [comment]
While I understand wanting to change the fee schedule, I don't think it should be. BTS prices may be down right now, but this market has been suffering all over. I think fees should remain as they are.

**Pull request merged**
