### PR TITLE
2018-11 update

### PR DESCRIPTION
**Pull request by xeroc**
Proposal by Alex/clockwork

**Details**
[2018-11-update-details.xlsx](https://github.com/bitshares/committee-tools/files/2629094/2018-11-update-details.xlsx)

### CODE REVIEW

**Comment by xeroc** [comment]
Consequences and differences (percentage-wise) can be found here:

https://gist.githubusercontent.com/xeroc/7e2c8989e64f68cd2964d3a6b8967b4c/raw/9d38a25fa852e825c0b235a5a58963aee94b29e3/2018-11-update.txt

**Comment by xeroc** [comment]
i am sure that CryptoBridge among other gateways will complain about the asset-issue fee being raised over 250% and i kind of agree. What a business would do to spare fee would be like Opebledger issue a lot of shares into gateway account and use transfers instead. There is added value (for transparency) when using asset-issue and reserve over transfer but its not worth 250%+ over transfers, IMHO

**Comment by xeroc** [comment]
```
Slavi La Libertad:
A typo? Or symbol4 is planned to be more costly than symbol3? :)
```

**Review by Agorise — COMMENTED** [review]
Demand dictates price. 
If Bitshares was not profitable then changes would need to be made. In its current state however, especially this bear market, demand is not dictating a price increase. What's worse, is price rises make mass-adoption more difficult, especially with "fee free" sites like Steemit using that as one of their biggest selling points. 
Demand dictates price. 
Please do NOT raise prices.

**Comment by CryptoKong** [comment]
"asset_claim_fees" - would it be possible to estimate a BTS value of asset fees to be claimed and take a percentage? Perhaps a percentage and minimum fee if the percentage is not high enough. This is the best point to take something back so that businesses profiting from the bitshares infrastructure contribute to its upkeep. The more trade fees an asset is making its issuer, the more they should contribute to the system that makes it possible.

**Comment by CryptoKong** [comment]
I would also suggest lowering witness pay.

**Comment by ThomasFreedman** [comment]
Doesn't make sense NOW, in this bear market to lower witness pay. I was in favor of doing that when prices were much higher, but now it makes very little sense, when witness pay has already decreased dramatically due to bear market prices, plus the number of witnesses has also increased from 21 to 27, a 22% decrease in pay just for that. Some witnesses are very near break even for server costs. 

As for asset creation fees going up so dramatically, I don't believe that makes sense either in a bear market. @Agorise has a point, market demand should be the gating factor. Raising prices for asset creation hurts those with less capital, for example entrepreneurs starting a new business, especially when they are not corporate giants or venture capital investors, but are individuals and those with small stakes.

It's not easy playing god with prices. Ideally the price should be set by Austrian principle of supply and demand, but we all know these puny crypto markets are highly manipulated due to their small size and obvious high demand by investors. Wall Street investors looking for any way they can to get involved with crypto, and there are a ton of them with huge capital to invest.

**Comment by liondani** [comment]
418 "limit_order_create" fee

Should not raised. We want as more as possible orders available on the order book!

**Comment by clockworkgr** [comment]
I just wanna point out that even at these updated prices, actual fees are still tiny.

Some individual points:

asset_create: still getting scam coins created.

asset_issue+asset_reserve: together still cost less than 1 transfer so still better for gateways to use for transparency instead of transfers. Still a tiny portion of gateway fees charged by gateways.

limit_order_create: still think the raised price is within reason

Also, percentage increases in @xeroc 's linked txt  in USD values seems even more excessive because BTS is at 35% the value it had when the previous fee schedule was made... Even if we WEREN'T changing agreed upon USD values, we would still have to raise them 2.8x in BTS terms (Everything with a change less than 2.8x the current one has actually been proposed cheaper..such as premium accounts from $5 to $3)

As far as WHY current fees are a problem, please read this:  https://steemit.com/bitshares/@clockwork/bitshares-fees-the-fee-schedule-and-dex-profitability

**Comment by bangzi1001** [comment]
Some witnesses stop providing price feed and some downgrade their servers due to big drop of BTS price. I suggest increase witnesses pay and so they will not downgrade their servers to save cost. Please note that BTS witnesses pay for at least one main witness server, one backup server and at least one API node server and I myself have extra one server for seed node.

**Comment by clockworkgr** [comment]
> Some witnesses stop providing price feed and some downgrade their servers due to big drop of BTS price. I suggest increase witnesses pay and so they will not downgrade their servers to save cost. Please note that BTS witnesses pay for at least one main witness server, one backup server and at least one API node server and I myself have extra one server for seed node.

I'm not suggesting we decrease pay for witnesses in this market.

However, let's keep things in perspective.
Publishing feeds for 15 assets , once every 15 minutes costs roughly 5 BTS per month.

Are you seriously suggesting witnesses stopped feeds to save 5 BTS a month?

Also, my API node, my witness server, my backup witness server, my testnet witness server(all hosted on expensive cloud providers) and my very highly specced public ES node (dedicated baremetal machine) + my subscriptions to APIs like currencylayer, bitcoinaverage, wuandl etc. cost a total of ~$900/month.

Witness pay at THIS BTS price is ~$1400.

Yeah, my time spent is worth over $500 imho but at the same time 3 months ago we were making $6-7k or more with the same costs.

So no, I don't agree with witness pay being increased (yet) unless this turns into a prolonged period of low BTS price.

Especially when costs are similar to what I described above and I know for a fact that MANY of the witnesses use very low spec machines as their mainnet witnesses to increase their profit margin.

**Comment by CryptoKong** [comment]
Perhaps witness pay should be a fixed dollar value and be recalculated every month/ 3 months.

**Comment by clockworkgr** [comment]
> Perhaps witness pay should be a fixed dollar value and be recalculated every month/ 3 months.

although not a bad idea, it's slightly more complex than that, because witness pay is per block produced...so blocks produced per month fluctuates as the number of witnesses change (although it's been a steady 27 for 4-5 months now)

**Comment by sschiessl-bcp** [comment]
@bangzi1001
Server pricing in Asia is quite different from EU. How much are the server costs for you currently?

**Comment by sschiessl-bcp** [comment]
While agree with most suggestions, the jump is quite significant, and no one likes jumps. 
I suggest to do this in steps and approximate the target fee schedule over a time range of e.g. 4 months. 
This allows to regularly adjust the fees to the current BTS value, and increase the costs gradually rather than jumpy.

For example:
`limit_order_create differs by   83.508x (network:    0.0004 USD / proposal:    0.0300 USD)`
The increase in USD would be `(0.0300 - 0.0004)/4 = 0.0074` each month, after 4 months the target fee is reached.

Comment on the content: `transfer` should be also 3 cents, rest inline

**Comment by PermieBTS** [comment]
Limit order create fee should not be so high to ensure maximum liquidity is provided to the DEX. 
$0.005 fee might not sound much but a Relative Orders Bot, which do provide a lot of the liquidity for the DEX can easily place and cancel orders 10 times before it makes a successful trade.. And the trade may even only maybe a few cents in profit. Tight spreads, which are highly desirable to our BTS exchange customers, mean tight profits for the traders and bots providing those spreads. Tight profits means a low tolerance for fee paying. 

Liquidity is the lifeblood on an exchange. Higher liquidity = a more useful exchange. High Limit order create&cancel fees heavily punish those who are providing liquidity. 
Limit order create fees place a tangible restriction on the lowest possible spread that the DEX is able to offer.  

Taker fees could be higher though, users buying the book and taking orders off the market is "undesirable" from the perspective of BTS the network. Order-taking reduces liquidity and can therefore be "punished" by fees paid to the network to compensate for the damage to liquidity 

However, transfer/send transactions cost the BitShares network. A higher number of transfer/send transactions does not provide more utility to DEX users in the same way that a high number of limit order create tx do. 

I think the cost to send a tx on the BitShares network should be no less than 50% cheaper than its competitor. 
Which major crypto has the next lowest tx fee? 
Customer psychology also has the strange occurrance that a supercheap price must be too good to be true and scares them away

**Comment by cloud-8** [comment]
Agree Limit order create fee is too high in this proposal and problematic to community projects like DEXbot (which has about 1m BTS+ many other UIAs currently making markets 24/7) which rely on multiple small order transactions.

**Comment by Kwaskoff** [comment]
When fee is minimal - people make more orders = more liquidity
BitShares need more liquidity and new users right now.

**Comment by froooze** [comment]
We should use the update to improve the fee schedule. Fees should be as low as possible and as high as needed. In this version some fees are too high.

- Taker/Maker fee
The taker is like sending an amount, the maker only makes an offer. 
Taker fee: 0.01$ (x50)
Maker fee: 0.001$ (and taker fee for margin calls) (x5)
Delete order: 0.0001$ (x5)
Limit order update: 0.0001$  (should be not higher than delete an order and make a new one)
 

- Sending BTS fee: 0.02$ (x6) (compared with Litecoin: 0.01$, Dash: 0.02$)
When gateways have a huge fees we should not do the same. Sending an asset is only 1% of the blockchain activity.

- Fees in $ with auto update:
The worker are paid in Dollar and fees are also better defined in Dollar for now. Prices need an automatic weekly price update. 

- One error:
There are both **0** decimals missing.
[ 0]  fee price for  transfer    12.353x (network:    0.00**0**65 USD / proposal:    0.0**0**800 USD)

**Comment by xeroc** [comment]
@PermieBTS @cloud-8 @Kwaskoff 

you might have forgotten that canceling a unmatched order will result in a refund of the order-creation fee

**Comment by CryptoKong** [comment]
There is a lot of concern here about fees affecting liquidity and rightly so. I know this is more about blockchain operation fees but a maker/ taker schedule should be considered for committee controlled assets in order to reward market makers and encourage people to place orders rather than fill them.

**Comment by cogutvalera** [comment]
the liquidity is the biggest problem for BitShares and if fees for orders will be higher than now then we would see even less liquidity. We have to solve liquidity problem and not to make this problem harder for solving.

**Comment by abitmore** [comment]
> ... at the same time 3 months ago we were making $6-7k or more with the same costs.

I guess you're not suggesting that witnesses should sell their earned BTS immediately when got paid?

> a fact that MANY of the witnesses use very low spec machines as their mainnet witnesses to increase their profit margin.

It's voters' job to vote out the unqualified ones.
It's supposed that higher pay will attract better candidates.

**Comment by clockworkgr** [comment]
> > ... at the same time 3 months ago we were making $6-7k or more with the same costs.
> 
> I guess you're not suggesting that witnesses should sell their earned BTS immediately when got paid?

No I'm not... It's in direct comparison to Bangzi's comment. He's the one that mentioned how "current" price forces them to shut down.

> 
> > a fact that MANY of the witnesses use very low spec machines as their mainnet witnesses to increase their profit margin.
> 
> It's voters' job to vote out the unqualified ones.
> It's supposed that higher pay will attract better candidates.

Voters unfortunately do not know how witnesses perform (apart from price-feeds) or whether they're running the claimed hardware.

Much higher pay will attract more unqualified candidates imho who will see it as an easy way to make money without necessarily being up to par when needed. Also, we might see people paying for votes (if they can afford to) which we have kinda avoided so far.

In any case, you know very well that I was the first to suggest possibly increasing pay for witnesses if this low price remains past the holidays. I am also a witness myself.

I just think that suggesting witnesses are stopping price feeds to save 5 BTS/month or that they rely on the "entire" monthly pay each month hence they can't weather 1-2 "bad" months is overstating things.

I've just had to cash out 50k BTS to pay for this month's costs + extra pay for me due to some extra end-of-year personal expenses while monthly pay is 28.8k BTS but that's fine. Let's not treat the reserve pool like a cash-cow

**Comment by clockworkgr** [comment]
Overall, there are some interesting observations here.

Some I agree with, some i don't while others are not possible at this stage.

I will be doing a small update to the proposed fee schedule according to them while also proposing we follow stefan's suggestion of doing it incrementally

**Comment by xeroc** [comment]
To make one thign clear here:
1. The increased limit_order_create fee does not affect liquidity providers because providing liquidity is basically for free due to the full refund of the creation fee in case of cancellation.
It might affect the volume and the spreads which include the increased fee in case of matching orders, but that's up to the businesses to deside.

2. Maker/Taker fee is not available on BitShares unless it is implemented with a network upgrade, so demanding it for this fee schedule update is waste of time. Committee simply cannot do it.

3. Witness pay is not yet part of this schedule. The schedule is for "income" (transaction fees) only so far.

**Comment by froooze** [comment]
@xeroc & @clockworkgr:
- Placing small orders (1$) is not anymore profitable, because the order fee is now 0.016$, which results over 1% in fee. 
- Integration for IoT is not anymore attractive
- High flat fees hit the unbanked/poor people the hardest 
- Liquidity provider still has to pay order cancel fee with 0.0016$ (0.16%)

Integration and liquidity bots are the most important things, high fees are just against this.

We can raise the fee for limit_order_create by 5 times. After a hardfork the taker fee can be 50 times bigger, than now and finance the maker fee.

We should not get greedy now and overdo the fee schedule. When sending an asset costs more, than on the Dash network, we are not cheap anymore.

Fee logic: Sending Asset > Taker Fee > Maker Fee > Cancel Order

**Comment by clockworkgr** [comment]
> @xeroc & @clockworkgr:
> 
> * Placing small orders (1$) is not anymore profitable, because the order fee is now 0.016$, which results over 1% in fee.
> * Integration for IoT is not anymore attractive
> * High flat fees hit the unbanked/poor people the hardest
> * Liquidity provider still has to pay order cancel fee with 0.0016$ (0.16%)
> 
> Integration and liquidity bots are the most important things, high fees are just against this.
> 
> We can raise the fee for limit_order_create by 5 times. After a hardfork the taker fee can be 50 times bigger, than now and finance the maker fee.
> 
> We should not get greedy now and overdo the fee schedule. When sending an asset costs more, than on the Dash network, we are not cheap anymore.
> 
> Fee logic: Sending Asset > Taker Fee > Maker Fee > Cancel Order

erm... Limit Order fee (if filled) is 0.006 for LTMs (i.e. 0.6% on a 1$ order....0.3% on a 2$ and negligible there after)

I agree with  treating maker/taker separately as soon as we have the ability to do so.

Many chains have lower transfer fees than us. And I'm against using "we're the cheapest!" as a marketing trick.  there are literally hundreds of other  reasons why people should use BitShares instead.

**Comment by jonathanbahai** [comment]
Our biggest money maker is in our asset sales. 

[10]                 symbol3 price for                              asset_create differs by    1.042x (network: 2878.5366 USD / proposal: 3000.0000 USD)
[10]                 symbol4 price for                              asset_create differs by   13.896x (network:  719.6341 USD / proposal: 10000.0000 USD)
[10]             long_symbol price for                              asset_create differs by    5.558x (network:   17.9909 USD / proposal:  100.0000 USD)

This area is clearly off somehow where we symbol4 somehow priced higher than symbol3. Perhaps missing a zero in symbol3 as I would support a $30k price on that. Long symbol price seems somewhat low though and can perhaps be better served with a 5X increase to be around the $500 mark. 

As for the market order increases. I think they should be adjusted by 5x and canceled orders should remain zero fee. I believe the market will bear this and liquidity would be unaffected that those levels. That is just an opinion based on sentiments not on analysis though. So to be clear:

[ 1]                     fee price for                        limit_order_create differs by   83.508x (network:    0.0004 USD / proposal:    0.0300 USD)
[ 2]                     fee price for                        limit_order_cancel differs by   84.680x (network:    0.0000 USD / proposal:    0.0030 USD)

Should be:

[ 1]                     fee price for                        limit_order_create differs by   5.000x (network:    0.0004 USD / proposal:    0.0020 USD)
[ 2]                     fee price for                        limit_order_cancel differs by   5.000x (network:    0.0000 USD / proposal:    0.0000 USD)

**Comment by clockworkgr** [comment]
> Our biggest money maker is in our asset sales.
> 
> [10] symbol3 price for asset_create differs by 1.042x (network: 2878.5366 USD / proposal: 3000.0000 USD)
> [10] symbol4 price for asset_create differs by 13.896x (network: 719.6341 USD / proposal: 10000.0000 USD)
> [10] long_symbol price for asset_create differs by 5.558x (network: 17.9909 USD / proposal: 100.0000 USD)
> 
> This area is clearly off somehow where we symbol4 somehow priced higher than symbol3. Perhaps missing a zero in symbol3 as I would support a $30k price on that. Long symbol price seems somewhat low though and can perhaps be better served with a 5X increase to be around the $500 mark.
> 
> As for the market order increases. I think they should be adjusted by 5x and canceled orders should remain zero fee. I believe the market will bear this and liquidity would be unaffected that those levels. That is just an opinion based on sentiments not on analysis though. So to be clear:
> 
> [ 1] fee price for limit_order_create differs by 83.508x (network: 0.0004 USD / proposal: 0.0300 USD)
> [ 2] fee price for limit_order_cancel differs by 84.680x (network: 0.0000 USD / proposal: 0.0030 USD)
> 
> Should be:
> 
> [ 1] fee price for limit_order_create differs by 5.000x (network: 0.0004 USD / proposal: 0.0020 USD)
> [ 2] fee price for limit_order_cancel differs by 5.000x (network: 0.0000 USD / proposal: 0.0000 USD)

symbol3/symbol4 error was corrected

In general , it's worth looking at the XLS which also has usage data and (rough) expected revenue etc.

**Comment by froooze** [comment]
@clockworkgr:
- When taking about fees, we should use the standard fee, because not everybody has or wants a LTM.
- We have a consensus, that we can rise the fee for limit_order_create and delete_order by 5 times without any impact on liquidity.
- Where is the maximum increasing point? I see it at 25 times (0.005$). Everything above 25 times is just too much. This could be a good compromise. What do you think?

**Comment by clockworkgr** [comment]
> @clockworkgr:
> 
> * When taking about fees, we should use the standard fee, because not everybody has or wants a LTM.
> * We have a consensus, that we can rise the fee for limit_order_create and delete_order by 5 times without any impact on liquidity.
> * Where is the maximum increasing point? I see it at 25 times (0.005$). Everything above 25 times is just too much. This could be a good compromise. What do you think?

I do use the standard fee normally, but the argument is that this fee affects bots/market-makers negatively. IMO, if you wanna run a market making bot on BitShares, you should invest in an LTM subscription.

Also, the agreed upon fee from the last fee schedule update was 0.001 for limit orders. As I mentioned, even if we simply updated fees today using the previous fee schedule (simply set the right BTS prices), we're still looking at a 500% increase in BTS terms

**Comment by froooze** [comment]
@clockworkgr:
> Also, the agreed upon fee from the last fee schedule update was 0.001 for limit orders. 

Please use units after your numbers! 

What do you think about the compromise "only" rising the fee 25x (0.005$/0.00125$)  instead of 84x? Where does the number of 84x come?

**Comment by clockworkgr** [comment]
> > Also, the agreed upon fee from the last fee schedule update was 0.001 for limit orders.
> > Please use units after your numbers!
> 
> What do you think about the compromise only rising the fee 25x instead of 84x? Where does the number of 84x bigger come?

it's new price vs current price....but current price is WAY lower than it should be cause BTS has dropped to like 20% since last fee adjustment

**Comment by clockworkgr** [comment]
> @clockworkgr:
> 
> > Also, the agreed upon fee from the last fee schedule update was 0.001 for limit orders.
> 
> Please use units after your numbers!
> 

Apologies...still talking about USD

**Comment by CryptoKong** [comment]
I agree with alex that more sophisticated users such as bot users should be expected to purchase lifetime memberships in order to reap the benefits of cheap fees for high usage.

**Comment by clockworkgr** [comment]
Updated a few things based on community feedback and posted a new proposal here: https://github.com/bitshares/committee-tools/pull/2

Also put it on the forums for further discussion.

**Comment by xeroc** [comment]
Superseeded by https://github.com/bitshares/committee-tools/pull/2

**Pull request closed without merging**
